version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    depends_on:
      - app
    networks:
      - shortness_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

  postgres:
    image: postgres:17
    container_name: shortness-postgres
    ports:
      - "${POSTGRES_PORT_MAPPING}"
    networks:
      - shortness_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:8.4.0
    container_name: shortness-redis
    ports:
      - "${REDIS_PORT_MAPPING}"
    networks:
      - shortness_network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: shortness-app
    networks:
      - shortness_network
    ports:
      - "${APP_PORT_MAPPING}"
    environment:
      - APP_HOST=${APP_HOST}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    command: sh -c "sleep 10 && java -jar build/service.jar"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - shortness_network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    networks:
      - shortness_network
    ports:
      - "${GRAFANA_ACCESS_IP}:${GRAFANA_ACCESS_PORT}:${GRAFANA_CONTAINER_PORT}"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - shortness_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  shortness_network:
    external: true